// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: namishs gui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void type1(lv_event_t * e);
void type2(lv_event_t * e);
void type3(lv_event_t * e);
void type4(lv_event_t * e);
void type5(lv_event_t * e);
void type6(lv_event_t * e);
void type7(lv_event_t * e);
void type8(lv_event_t * e);
void type9(lv_event_t * e);
void type0(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
