// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: namishs gui

#include "../ui.h"


// COMPONENT Password Area

lv_obj_t * ui_Password_Area_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Password_Area;
    cui_Password_Area = lv_textarea_create(comp_parent);
    lv_obj_set_width(cui_Password_Area, 135);
    lv_obj_set_height(cui_Password_Area, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(cui_Password_Area, 333);
    lv_obj_set_y(cui_Password_Area, 100);
    lv_obj_set_align(cui_Password_Area, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(cui_Password_Area, 6);
    lv_textarea_set_placeholder_text(cui_Password_Area, "Enter Password");
    lv_textarea_set_one_line(cui_Password_Area, true);
    lv_textarea_set_password_mode(cui_Password_Area, true);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PASSWORD_AREA_NUM);
    children[UI_COMP_PASSWORD_AREA_PASSWORD_AREA] = cui_Password_Area;
    lv_obj_add_event_cb(cui_Password_Area, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Password_Area, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Password_Area_create_hook(cui_Password_Area);
    return cui_Password_Area;
}

