// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: namishs gui

#ifndef _NAMISHS_GUI_UI_H
#define _NAMISHS_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Home_Screen
void ui_Home_Screen_screen_init(void);
extern lv_obj_t * ui_Home_Screen;
void ui_event_Password_Button(lv_event_t * e);
extern lv_obj_t * ui_Password_Button;
extern lv_obj_t * ui_Go_To_Password;
void ui_event_Scan_RFID(lv_event_t * e);
extern lv_obj_t * ui_Scan_RFID;
extern lv_obj_t * ui_Go_To_RFID;
extern lv_obj_t * ui_Image1;
// SCREEN: ui_Password_Screen
void ui_Password_Screen_screen_init(void);
extern lv_obj_t * ui_Password_Screen;
extern lv_obj_t * ui_Text_Input;
extern lv_obj_t * ui_Text_input;
void ui_event_Backspace_Button(lv_event_t * e);
extern lv_obj_t * ui_Backspace_Button;
extern lv_obj_t * ui_Backspace_Label;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label9;
void ui_event_Button0(lv_event_t * e);
extern lv_obj_t * ui_Button0;
extern lv_obj_t * ui_Label0;
void ui_event_Back_Button(lv_event_t * e);
extern lv_obj_t * ui_Back_Button;
extern lv_obj_t * ui_Back_Label;
// SCREEN: ui_RFID_Screen
void ui_RFID_Screen_screen_init(void);
extern lv_obj_t * ui_RFID_Screen;
extern lv_obj_t * ui_Label;
void ui_event_Back_Button2(lv_event_t * e);
extern lv_obj_t * ui_Back_Button2;
extern lv_obj_t * ui_Back_Label2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1525890679);    // assets/Designer-removebg-preview.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
