// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: namishs gui

#include "ui.h"

void erase(lv_event_t * e)
{
	// Your code here
}
