// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ArduinoSecurityGUI

#ifndef _UI_COMP_PASSWORD_AREA_H
#define _UI_COMP_PASSWORD_AREA_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Password Area
#define UI_COMP_PASSWORD_AREA_PASSWORD_AREA 0
#define _UI_COMP_PASSWORD_AREA_NUM 1
lv_obj_t * ui_Password_Area_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
