// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: namishs gui

#include "ui.h"

void type1(lv_event_t * e)
{
	// Your code here
}

void type2(lv_event_t * e)
{
	// Your code here
}

void type3(lv_event_t * e)
{
	// Your code here
}

void type4(lv_event_t * e)
{
	// Your code here
}

void type5(lv_event_t * e)
{
	// Your code here
}

void type6(lv_event_t * e)
{
	// Your code here
}

void type7(lv_event_t * e)
{
	// Your code here
}

void type8(lv_event_t * e)
{
	// Your code here
}

void type9(lv_event_t * e)
{
	// Your code here
}

void type0(lv_event_t * e)
{
	// Your code here
}
