// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: namishs gui

#include "../ui.h"

void ui_Home_Screen_screen_init(void)
{
    ui_Home_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Title = lv_label_create(ui_Home_Screen);
    lv_obj_set_width(ui_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Title, 0);
    lv_obj_set_y(ui_Title, -180);
    lv_obj_set_align(ui_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Title, "GRIZZLY GUARDIAN");
    lv_label_set_recolor(ui_Title, "true");
    lv_obj_set_style_text_color(ui_Title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Title, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Password_Button = lv_btn_create(ui_Home_Screen);
    lv_obj_set_width(ui_Password_Button, 150);
    lv_obj_set_height(ui_Password_Button, 50);
    lv_obj_set_x(ui_Password_Button, -100);
    lv_obj_set_y(ui_Password_Button, 0);
    lv_obj_set_align(ui_Password_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Password_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Password_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Go_To_Password = lv_label_create(ui_Password_Button);
    lv_obj_set_width(ui_Go_To_Password, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Go_To_Password, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Go_To_Password, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Go_To_Password, "Use Password");

    ui_Scan_RFID = lv_btn_create(ui_Home_Screen);
    lv_obj_set_width(ui_Scan_RFID, 150);
    lv_obj_set_height(ui_Scan_RFID, 50);
    lv_obj_set_x(ui_Scan_RFID, 100);
    lv_obj_set_y(ui_Scan_RFID, 0);
    lv_obj_set_align(ui_Scan_RFID, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scan_RFID, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Scan_RFID, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Go_To_RFID = lv_label_create(ui_Scan_RFID);
    lv_obj_set_width(ui_Go_To_RFID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Go_To_RFID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Go_To_RFID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Go_To_RFID, "Scan RFID");

    lv_obj_add_event_cb(ui_Password_Button, ui_event_Password_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Scan_RFID, ui_event_Scan_RFID, LV_EVENT_ALL, NULL);

}
