// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ArduinoSecurityGUI

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea1, 285);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_TextArea1, 219);
    lv_obj_set_y(ui_TextArea1, 82);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Enter Password");
    lv_textarea_set_one_line(ui_TextArea1, true);
    lv_textarea_set_password_mode(ui_TextArea1, true);



    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard1, 533);
    lv_obj_set_height(ui_Keyboard1, 295);
    lv_obj_set_x(ui_Keyboard1, -30);
    lv_obj_set_y(ui_Keyboard1, 76);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);


}
