// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ArduinoSecurity

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_Switch1, 330);
    lv_obj_set_height(ui_Switch1, 33);
    lv_obj_set_x(ui_Switch1, -12);
    lv_obj_set_y(ui_Switch1, -46);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);



}
